### ISSUE TITLE
Vim Mode :) 

### ISSUE THREAD

**Issue by 11** [dqgorelick/tabbo#13]
- `meta + shift + h` or `meta + shift + l` move your current tab over one position left or right in the tab bar 

- `2 + meta + shift + h` or `2 + meta + shift + l` move your current tab over two positions left or right in the tab bar -- substitute 2 for _n_ amount of tabs. 

- `meta + h` or `meta + l` to move to the previous/next tab

- `2 + meta + h` or `2 + meta + l` to move 2 previous/next tabs -- substitute 2 for _n_ amount of tabs

**Comment by dqgorelick** [comment]
@11 serious issue requests only please.
