### ISSUE TITLE
Multi tab selection doesn't work

### ISSUE THREAD

**Issue by turkeyphant** [dqgorelick/tabbo#30]
In Chrome you can select multiple tabs by holding down `shift` or `ctrl` but this doesn't work with Tabbo.

**Comment by jwoos** [comment]
We're aware of this issue :) It's kind of tricky to solve due to how multi tab selection works - they don't have to be sequential. I tried implementing it a while ago but never got around to finishing it. I might take a look again soon when I have time

**Comment by jwoos** [comment]
refer to #2
