### ISSUE TITLE
Use i3wm workspace number as target hotkey in tabbo dashboard

### ISSUE THREAD

**Issue by ioanniswd** [dqgorelick/tabbo#50]
I am using i3wm and have browser windows in multiple workspaces. It would be more intuitive if, on the tabbo dashboard where I am supposed to choose the window to which to move the tab, I could type the number of the **workspace** the target window is in, to send the tab.
Not sure if this is possible, just an idea.

**Comment by jwoos** [comment]
Hey, thanks for the suggestion :) I used to use i3 myself so I definitely see where you're coming from. I can look into it but I have a feeling it won't be feasible

**Comment by jwoos** [comment]
closing this one out, given it's window manager specific :(
