### ISSUE TITLE
Omit PWA windows on Chrome

### ISSUE THREAD

**Issue by FranklinYu** [dqgorelick/tabbo#73]
[PWA windows](https://web.dev/progressive-web-apps/) doesn’t accept tabs anyway, so we should omit them in the window list. I’m not sure how feasible is this (e.g. whether Chrome provides an API to distinguish PWA windows, but in the worse case we can provide an option to “skip single-tab windows” and that should work for most of the scenarios.

**Comment by dqgorelick** [comment]
Thanks for bringing this up. Can you describe the use-case in a bit more detail? When you say "window list" are you referring to the "send tab" page?

**Comment by FranklinYu** [comment]
Yes, exactly. I frequently use the command to launch the “send tab” page, then pressing the number to send the associated tab to the corresponding window. If I accidentally send it to a PWA window, it won’t be moved there (because Chrome won’t let you), so I have to trigger the command again.

**Comment by FranklinYu** [comment]
(Let me know if you are still confused about what I meant.)

**Comment by FranklinYu** [comment]
After some research this seems feasible. The right way to detect PWA windows is via media query: the `display-mode` would be [`standalone`](https://developer.mozilla.org/en-US/docs/Web/CSS/@media/display-mode#standalone) in that case. Since we already have `<all_urls>` permission we can add a content script to do [Window.matchMedia()](https://developer.mozilla.org/en-US/docs/Web/API/Window/matchMedia) and post a message with the query result. How does this plan sound to you?
